/**
 * Retours de testeuses RÉELLES — produit reçu en avant-première (pas un achat).
 * Honnête et conforme (directive Omnibus / DGCCRF) :
 *   - PAS de « achat vérifié » (elles n'ont pas acheté) → libellé « Testeuse ».
 *   - PAS de compteurs « utile » inventés, PAS de stats d'efficacité non prouvées.
 *   - Citations = opinions individuelles, affichées avec la mention « résultats
 *     individuels, non garantis ». Prénom + ville publiés avec leur accord.
 * Source : panel de 30 testeuses, 4 semaines. Mettre à jour si la liste évolue.
 */

export type SkinType = "grasse" | "mixte" | "sensible";

export type Tester = {
  name: string;
  city: string;
  age: number;
  type: SkinType;
  tag: string;
  title: string;
  body: string;
  highlight?: string;
};

export const TESTERS: Tester[] = [
  {
    name: "Amina B.",
    city: "Lyon",
    age: 24,
    type: "grasse",
    tag: "Peau grasse",
    title: "Enfin un sérum qui ne me fait pas briller à midi",
    body: "J'ai testé une dizaine de sérums en 2 ans. Celui-là est le premier qui tient sa promesse sur le sébum. À J7 ma zone T était déjà moins luisante. Mon fond de teint tient toute la journée maintenant.",
    highlight: "Mes pores du nez ont l'air deux fois plus petits sur mes photos.",
  },
  {
    name: "Camille R.",
    city: "Paris 11e",
    age: 27,
    type: "mixte",
    tag: "Peau mixte",
    title: "Ma routine réduite à ce sérum",
    body: "Texture ultra légère, s'absorbe en quelques secondes. J'ai allégé ma routine car ce sérum hydrate sans alourdir. Ma peau est plus nette et le teint plus égal.",
  },
  {
    name: "Sofia M.",
    city: "Marseille",
    age: 22,
    type: "sensible",
    tag: "Peau sensible",
    title: "Zéro réaction, et un vrai résultat",
    body: "Ma peau réagit à tout, j'ai hésité longtemps. Aucune rougeur, aucune irritation. Après 3 semaines mes marques d'imperfections ont visiblement estompé. La Centella fait vraiment son travail.",
  },
  {
    name: "Jade K.",
    city: "Bordeaux",
    age: 21,
    type: "grasse",
    tag: "Peau grasse à imperfections",
    title: "Ma peau de février ne s'est pas emballée",
    body: "Chaque printemps mon visage s'emballe. Pendant le test, beaucoup plus calme. Le combo niacinamide + Centella, j'aurais aimé l'essayer bien avant.",
  },
  {
    name: "Léa T.",
    city: "Nantes",
    age: 26,
    type: "mixte",
    tag: "Peau mixte",
    title: "La texture est un plaisir au quotidien",
    body: "J'utilisais un sérum à 65 € avant. Là, résultats similaires voire meilleurs, et une texture que j'attends le matin. L'emballage est magnifique en plus.",
  },
  {
    name: "Inès A.",
    city: "Toulouse",
    age: 23,
    type: "grasse",
    tag: "Peau grasse",
    title: "Sceptique au début… plus maintenant",
    body: "Je pensais que c'était un sérum de plus. Mais à J14, deux petites imperfections persistantes sur mon front s'étaient nettement apaisées. Bluffée.",
  },
  {
    name: "Manon D.",
    city: "Rennes",
    age: 25,
    type: "sensible",
    tag: "Peau sensible mixte",
    title: "Testé pendant une période de stress intense",
    body: "Examens de fin d'année = peau qui part en vrille d'habitude. Cette fois, la Centella a vraiment calmé mes rougeurs. Mon teint est resté stable malgré le manque de sommeil.",
  },
  {
    name: "Noémie G.",
    city: "Lille",
    age: 28,
    type: "mixte",
    tag: "Peau mixte",
    title: "Je n'évite plus mon miroir",
    body: "Avant je ne regardais jamais ma peau sans maquillage. Maintenant j'ai presque pas envie de me couvrir. Teint plus lumineux, pores affinés, texture du sérum très agréable.",
  },
  {
    name: "Emma V.",
    city: "Strasbourg",
    age: 20,
    type: "grasse",
    tag: "Peau grasse",
    title: "J'ai arrêté les lingettes matifiantes",
    body: "Je consommais deux paquets de lingettes par mois tellement ma peau brillait. Pendant le test, je n'en ai plus eu besoin. Tamponner mon front à 14h, c'est du passé.",
  },
  {
    name: "Chloé B.",
    city: "Paris 18e",
    age: 29,
    type: "sensible",
    tag: "Peau réactive",
    title: "Doux, même sur une peau capricieuse",
    body: "Avec ma peau réactive, je suis très prudente. J'ai commencé deux fois par semaine. Aucune réaction. Maintenant matin et soir, et mes rougeurs ont diminué de façon visible.",
  },
  {
    name: "Alicia F.",
    city: "Nice",
    age: 24,
    type: "mixte",
    tag: "Peau mixte",
    title: "Un teint plus égal dès la première semaine",
    body: "Je ne pensais pas voir une différence aussi vite. Dès le 5e jour mon teint était plus uniforme. À J21, on m'a demandé si j'avais changé de fond de teint. Non, juste le sérum.",
  },
  {
    name: "Sarah L.",
    city: "Montpellier",
    age: 22,
    type: "grasse",
    tag: "Peau grasse à imperfections",
    title: "Je poste à nouveau des photos sans filtre",
    body: "Je mettais toujours un filtre sur mes stories. Là je poste en brut. Mes marques se sont estompées et la texture de ma peau s'est lissée. Ça a changé le regard que je porte sur mon visage.",
  },
  {
    name: "Océane P.",
    city: "Bordeaux",
    age: 26,
    type: "mixte",
    tag: "Peau mixte",
    title: "Une sensation de peau propre toute la journée",
    body: "Détail qui compte : l'odeur est neutre et agréable. Pas d'alcool agressif, pas de parfum synthétique. La texture glisse parfaitement. C'est rare.",
  },
  {
    name: "Mathilde C.",
    city: "Lyon",
    age: 30,
    type: "sensible",
    tag: "Peau sensible",
    title: "Je l'ai fait tester à ma sœur et ma mère",
    body: "On a comparé nos peaux après 3 semaines toutes les trois. Chacune a vu une amélioration nette, sur des peaux pourtant différentes. Polyvalent et doux.",
  },
  {
    name: "Kenza H.",
    city: "Paris 9e",
    age: 23,
    type: "grasse",
    tag: "Peau grasse",
    title: "La niacinamide qui fait vraiment son effet",
    body: "Je connaissais la niacinamide via TikTok, sans jamais voir de vrai résultat. Là c'est différent : en 10 jours mes pores étaient visiblement affinés. Le dosage doit être bien pensé.",
  },
  {
    name: "Valentine R.",
    city: "Rennes",
    age: 27,
    type: "mixte",
    tag: "Peau mixte déshydratée",
    title: "Hydratée sans être grasse, enfin",
    body: "Ma peau était mixte ET déshydratée : joues qui tiraillent, front qui brille. Un casse-tête. naeul équilibre les deux zones. Enfin un sérum qui comprend ma peau.",
    highlight: "Le premier soin qui ne me force pas à choisir entre brillance et tiraillements.",
  },
  {
    name: "Tiffany N.",
    city: "Nantes",
    age: 21,
    type: "grasse",
    tag: "Peau grasse",
    title: "Mon maquillage tient bien plus longtemps",
    body: "Depuis que j'applique le sérum le matin avant ma BB cream, mon maquillage est encore net le soir. Avant il partait en milieu d'après-midi.",
  },
  {
    name: "Anaïs W.",
    city: "Dijon",
    age: 25,
    type: "sensible",
    tag: "Peau sensible",
    title: "Doux, progressif, mais bien réel",
    body: "J'avais arrêté les soins trop forts car ma peau devenait fragile. naeul est ma première routine douce depuis un an. Résultat progressif, mais réel. J'aurais dû changer avant.",
  },
  {
    name: "Pauline B.",
    city: "Paris 3e",
    age: 28,
    type: "mixte",
    tag: "Peau mixte",
    title: "J'ai trouvé mon sérum signature",
    body: "Je cherchais depuis 2 ans le sérum que je garderais sur le long terme. La texture, l'efficacité, les ingrédients propres, le prix : tout coche. J'ai hâte de le racheter au lancement.",
  },
  {
    name: "Diana O.",
    city: "Grenoble",
    age: 22,
    type: "grasse",
    tag: "Peau grasse",
    title: "Même mon copain a remarqué",
    body: "Sans que je lui dise quoi que ce soit, il m'a dit « ta peau a l'air différente, plus nette ». C'est lui mon meilleur indicateur, il ne remarque jamais ce genre de chose d'habitude.",
  },
  {
    name: "Laura S.",
    city: "Toulouse",
    age: 24,
    type: "sensible",
    tag: "Peau sensible",
    title: "Stable, même quand le temps change",
    body: "J'ai testé sur plusieurs semaines, dont des journées chaudes. Ma peau ne réagit pas différemment. Un sérum qui ne m'oblige pas à gérer deux routines selon la saison, c'est précieux.",
  },
  {
    name: "Romane J.",
    city: "Lille",
    age: 23,
    type: "mixte",
    tag: "Peau mixte",
    title: "Le flacon attire, le produit confirme",
    body: "Je suis honnête : l'esthétique du flacon m'a attirée, et j'avais peur que ce soit que du visuel. Pas du tout. Résultats concrets, ingrédients sérieux, formule qui tient ses promesses.",
  },
  {
    name: "Mia T.",
    city: "Paris 20e",
    age: 20,
    type: "grasse",
    tag: "Peau grasse",
    title: "Les certifications m'ont mise en confiance",
    body: "Je lis les compositions depuis des années. La certification ECOCERT m'a convaincue d'essayer, et derrière, les actifs font leur job. Une marque qu'on sent sérieuse.",
  },
  {
    name: "Zoé M.",
    city: "Strasbourg",
    age: 26,
    type: "sensible",
    tag: "Peau sensible",
    title: "Une composition cohérente",
    body: "J'ai montré la composition à mon esthéticienne, qui l'a trouvée cohérente avec ce qu'elle utilise en cabine. Ça m'a rassurée avant de tester. Et le ressenti a suivi.",
  },
  {
    name: "Eléonore H.",
    city: "Nantes",
    age: 29,
    type: "mixte",
    tag: "Peau mixte",
    title: "Mes photos d'identité, enfin",
    body: "J'avais une photo officielle à faire. Pour la première fois je n'ai pas détesté le résultat : teint net, pores discrets. Petite victoire, mais qui compte pour moi.",
  },
  {
    name: "Bérénice L.",
    city: "Paris 15e",
    age: 25,
    type: "grasse",
    tag: "Peau grasse",
    title: "La première K-beauty qui m'a convaincue",
    body: "Je suis sceptique des tendances K-beauty. Mais les résultats sont là. Traiter le problème à la source plutôt que de le camoufler, ça se ressent dans la formule.",
  },
  {
    name: "Clara G.",
    city: "Lyon",
    age: 28,
    type: "sensible",
    tag: "Peau sensible",
    title: "Je vais le recommander autour de moi",
    body: "C'est rare que je recommande quelque chose avec autant de conviction. Résultats, formule clean, prix honnête : je compte l'offrir à mes amies dès le lancement.",
  },
  {
    name: "Farah K.",
    city: "Marseille",
    age: 24,
    type: "mixte",
    tag: "Peau mixte",
    title: "Adopté sans transition",
    body: "D'habitude je fais une transition douce avec les nouveaux produits. Là, matin et soir dès le premier jour, aucun souci. Ma peau n'a pas bronché. Formulé avec intelligence.",
  },
  {
    name: "Yasmine B.",
    city: "Paris 19e",
    age: 21,
    type: "grasse",
    tag: "Peau grasse à imperfections",
    title: "Mon mois a été beaucoup plus calme",
    body: "D'habitude, plusieurs imperfections autour du menton à chaque cycle. Pendant le test, beaucoup moins. Je crois beaucoup à l'effet de la barrière cutanée renforcée.",
    highlight: "Pour la première fois depuis mes 16 ans, ma routine ressemble à un soin, pas à une corvée.",
  },
  {
    name: "Julie M.",
    city: "Bordeaux",
    age: 27,
    type: "sensible",
    tag: "Peau sensible mixte",
    title: "Le sérum qui manquait à la beauté française",
    body: "La rigueur de la K-beauty, mais une marque française et certifiée : exactement ce que je cherchais. Les marques coréennes que j'achetais avaient les résultats, pas les certifications. Là, j'ai les deux.",
    highlight: "J'attendais cette marque sans le savoir.",
  },
];
